const componentsArray = [
  {
    id: 1,
    title: "Atualizado Em",
    label: "Atualizado Em",
    component: "I",
    type: "text",
    group: "property",
    icon: "fas fa-font-case",
    placeholder: "",
    prefix: null,
    suffix: null,
    hint: null,
    color: null,
    dense: true,
    style: {
      marginTop: 5,
      marginBottom: 5,
      marginRight: 5,
      marginLeft: 5,
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: 0,
      paddingLeft: 0,
    },
  },
  {
    id: 2,
    title: "Atualizado Por",
    label: "Atualizado Por",
    component: "I",
    type: "text",
    group: "property",
    icon: "fas fa-font-case",
    placeholder: "",
    hint: null,
    color: null,
    dense: true,
    style: {
      marginTop: 5,
      marginBottom: 5,
      marginRight: 5,
      marginLeft: 5,
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: 0,
      paddingLeft: 0,
    },
  },
  {
    id: 3,
    title: "Criado Em",
    label: "Criado Em",
    component: "I",
    type: "text",
    group: "property",
    icon: "fas fa-font-case",
    placeholder: "",
    hint: null,
    color: null,
    dense: true,
    style: {
      marginTop: 5,
      marginBottom: 5,
      marginRight: 5,
      marginLeft: 5,
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: 0,
      paddingLeft: 0,
    },
  },
  {
    id: 4,
    title: "Criado Por",
    label: "Criado Por",
    component: "I",
    type: "text",
    group: "property",
    icon: "fas fa-font-case",
    placeholder: "",
    hint: null,
    color: null,
    dense: true,
    style: {
      marginTop: 5,
      marginBottom: 5,
      marginRight: 5,
      marginLeft: 5,
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: 0,
      paddingLeft: 0,
    },
  },
  {
    id: 5,
    title: "Id",
    label: "Id",
    component: "I",
    type: "number",
    group: "property",
    icon: "123",
    placeholder: "",
    hint: null,
    color: null,
    dense: true,
    style: {
      marginTop: 5,
      marginBottom: 5,
      marginRight: 5,
      marginLeft: 5,
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: 0,
      paddingLeft: 0,
    },
  },
  {
    id: 6,
    title: "Painel com Abas",
    component: "Tabs",
    type: null,
    group: "element",
    icon: "tab",
    placeholder: false,
    color: null,
    dense: true,
    style: {
      marginTop: 0,
      marginBottom: 0,
      marginRight: 0,
      marginleft: 0,
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: 0,
      paddingLeft: 0,
    },
  },
  {
    id: 7,
    title: "Botão",
    component: "B",
    type: null,
    group: "element",
    icon: "smart_button",
    placeholder: false,
    color: null,
    dense: true,
    style: {
      marginTop: 0,
      marginBottom: 0,
      marginRight: 0,
      marginleft: 0,
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: 0,
      paddingLeft: 0,
    },
  },
  {
    id: 8,
    title: "Histórico",
    component: "History",
    type: null,
    group: "element",
    icon: "history_edu",
    placeholder: false,
    color: null,
    dense: true,
    style: {
      marginTop: 0,
      marginBottom: 0,
      marginRight: 0,
      marginleft: 0,
      paddingTop: 0,
      paddingBottom: 0,
      paddingRight: 0,
      paddingLeft: 0,
    },
  },
  {
    id: 18,
    title: "Section",
    component: "Section",
    type: null,
    group: "structure",
    icon: "fas fa-columns",
    placeholder: false,
    children: [
      {
        isFirst: true,
      },
    ],
    groups: ["property", "element"],
    color: null,
    dense: true,
    styles: {
      inline: {
        width:'100%',
        marginTop: 0,
        marginBottom: 0,
        marginRight: 0,
        marginleft: 0,
        paddingTop: 0,
        paddingBottom: 0,
        paddingRight: 0,
        paddingLeft: 0,
      }
    },
  },
  {
    id: 19,
    title: "Columns",
    component: "Columns",
    type: "1",
    group: "structure",
    icon: "fas fa-columns",
    placeholder: false,
    groups: ["sections"],
    children: [
      {
        id: 22,
        title: "Section",
        component: "Section",
        type: null,
        group: "structure",
        icon: "fas fa-columns",
        placeholder: false,
        children: [
          {
            isFirst: true,
          },
        ],
        groups: ["property", "element"],
        color: null,
        dense: true,
        styles: {
          inline: {
            width:'100%',
            marginTop: 0,
            marginBottom: 0,
            marginRight: 0,
            marginleft: 0,
            paddingTop: 0,
            paddingBottom: 0,
            paddingRight: 0,
            paddingLeft: 0,
          }
        },
      }
    ],
    color: null,
    dense: true,
    style: {
        marginTop: 0,
        marginBottom: 5,
        marginRight: 0,
        marginleft: 0,
        paddingTop: 5,
        paddingBottom: 0,
        paddingRight: 0,
        paddingLeft: 0,
    },
  },
  // {
  //   id: 20,
  //   title: "3 Columns",
  //   component: "Columns",
  //   type: "3",
  //   group: "structure",
  //   icon: "fas fa-columns",
  //   placeholder: false,
  //   groups: ["property", "element"],
  //   children: [],
  //   style: { margin: 0, padding: 0 },
  // },
  // {
  //   id: 21,
  //   title: "4 Columns",
  //   component: "Columns",
  //   type: "4",
  //   group: "structure",
  //   icon: "fas fa-columns",
  //   placeholder: false,
  //   groups: ["property", "element"],
  //   children: [],
  //   style: { margin: 0, padding: 0 },
  // },
];

export default componentsArray;
